local mod = get_mod("dpm_meter")

return {
    mod_name = {
        en = "DPM Meter",
        ["zh-cn"] = "DPM 伤害统计",
    },
    mod_description = {
        en = "Tracks Damage Per Minute with a smooth Discord-style animated text gradient.",
        ["zh-cn"] = "记录 DPM，以平滑的 Discord 风格动态文字渐变显示。",
    },
    position_group = { en = "Position", ["zh-cn"] = "位置" },
    number_group = { en = "Text and number animation", ["zh-cn"] = "文字与数字动画" },
    font_group = { en = "Font", ["zh-cn"] = "字体" },
    gradient_group = { en = "Gradient and shimmer", ["zh-cn"] = "渐变与流光" },
    panel_x_offset = { en = "Horizontal offset", ["zh-cn"] = "水平位置偏移" },
    panel_y_offset = { en = "Vertical offset", ["zh-cn"] = "垂直位置偏移" },
    font_size = { en = "Font size", ["zh-cn"] = "字体大小" },
    anim_speed = { en = "Number smoothing speed", ["zh-cn"] = "数字平滑速度" },
    font_type = { en = "Font", ["zh-cn"] = "字体选择" },
    font_option_proxima_nova_bold = { en = "Proxima Nova Bold", ["zh-cn"] = "Proxima Nova 粗体" },
    font_option_proxima_nova_medium = { en = "Proxima Nova Medium", ["zh-cn"] = "Proxima Nova 中号" },
    font_option_machine_medium = { en = "Machine Medium", ["zh-cn"] = "Machine 中号" },
    font_option_arial = { en = "Arial", ["zh-cn"] = "Arial" },
    font_option_trim_mono_bold = { en = "Trim Mono Bold", ["zh-cn"] = "Trim Mono 等宽粗体" },
    font_option_itc_novarese_medium = { en = "ITC Novarese Medium", ["zh-cn"] = "ITC Novarese 花体中号" },
    font_option_itc_novarese_bold = { en = "ITC Novarese Bold", ["zh-cn"] = "ITC Novarese 花体粗体" },
    font_option_friz_quadrata = { en = "Friz Quadrata", ["zh-cn"] = "Friz Quadrata 装饰体" },
    font_option_rexlia = { en = "Rexlia", ["zh-cn"] = "Rexlia 装饰体" },
    gradient_mode = { en = "Gradient mode", ["zh-cn"] = "渐变模式" },
    gradient_mode_custom = { en = "Custom colors", ["zh-cn"] = "自定义颜色" },
    gradient_mode_text = { en = "Follow base text color", ["zh-cn"] = "跟随基础文字颜色" },
    gradient_mode_off = { en = "Disable gradient", ["zh-cn"] = "关闭渐变" },
    gradient_color_count = { en = "Color stops", ["zh-cn"] = "渐变颜色数量" },
    gradient_colors_two = { en = "Two colors", ["zh-cn"] = "双色" },
    gradient_colors_three = { en = "Three colors", ["zh-cn"] = "三色" },
    gradient_animation = { en = "Gradient movement", ["zh-cn"] = "渐变运动" },
    gradient_animation_flow = { en = "Flowing", ["zh-cn"] = "动态流动" },
    gradient_animation_static = { en = "Static", ["zh-cn"] = "静态" },
    gradient_start_hex = { en = "Start color (#RRGGBB)", ["zh-cn"] = "起始颜色（#RRGGBB）" },
    gradient_middle_hex = { en = "Middle color (#RRGGBB)", ["zh-cn"] = "中间颜色（#RRGGBB）" },
    gradient_end_hex = { en = "End color (#RRGGBB)", ["zh-cn"] = "结束颜色（#RRGGBB）" },
    text_color_hex = { en = "Base text color (#RRGGBB)", ["zh-cn"] = "基础文字颜色（#RRGGBB）" },
    gradient_opacity = { en = "Gradient strength (0-100)", ["zh-cn"] = "渐变强度（0-100）" },
    gradient_animation_speed = { en = "Gradient speed", ["zh-cn"] = "渐变速度" },
    gradient_shimmer = { en = "Enable Discord-like shimmer", ["zh-cn"] = "启用 Discord 风格流光" },
    gradient_shimmer_speed = { en = "Shimmer speed", ["zh-cn"] = "流光速度" },
    gradient_shimmer_strength = { en = "Shimmer strength (0-1)", ["zh-cn"] = "流光强度（0-1）" },
    gradient_preview = { en = "Show live gradient preview", ["zh-cn"] = "显示实时渐变预览" },
    dpm_meter_text_input_noop = { en = "", ["zh-cn"] = "" },
}
